name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build
        env:
          MAINTAINER_EMAIL: ${{ github.event.pusher.email }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist-electron/*.exe
            dist-electron/*.AppImage
            dist-electron/*.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
